"""
config.py
=========
Central configuration for the Apollo Mode Choice Prediction pipeline.
All pipeline scripts import from this module — change settings here only.

Ollama Quick Setup (one-time):
  1. Install : https://ollama.com/download
  2. Pull    : ollama pull llama3.1          (~4.7 GB, recommended)
               ollama pull llama3.2:3b       (~2.0 GB, low-RAM option)
               ollama pull llama3.1:70b      (~40 GB,  GPU recommended)
  3. Start   : ollama serve
"""

import os
from dotenv import load_dotenv

# Load .env file (OLLAMA_MODEL, OLLAMA_BASE_URL, HF_TOKEN)
load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# DATA SELECTION
# Options: "SP_ONLY" | "RP_ONLY" | "BOTH"
#   SP_ONLY → Stated Preference (hypothetical scenarios, clean variation)
#   RP_ONLY → Revealed Preference (actual observed trips, real behaviour)
#   BOTH    → All trips combined (maximum data volume)
# ─────────────────────────────────────────────────────────────────────────────
DATA_TYPE: str = "SP_ONLY"

# ─────────────────────────────────────────────────────────────────────────────
# PATHS  (relative to project root; created automatically if missing)
# ─────────────────────────────────────────────────────────────────────────────
DATA_PATH: str = "data/raw/apollo_modeChoiceData.csv"
PROCESSED_DIR: str = "data/processed/"
PERSONAS_DIR: str = "data/personas/"
MODELS_DIR: str = "models/"
INSTRUCTION_DIR: str = "instruction_dataset/"
OUTPUTS_DIR: str = "outputs/"
LOGS_DIR: str = "logs/"

# Auto-create all output directories on import
for _dir in [PROCESSED_DIR, PERSONAS_DIR, MODELS_DIR, INSTRUCTION_DIR, OUTPUTS_DIR, LOGS_DIR]:
    os.makedirs(_dir, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# COLUMN DEFINITIONS
# ─────────────────────────────────────────────────────────────────────────────
TRAVELER_ID_COL: str = "ID"
LABEL_COL: str = "choice"

# Integer → mode name mapping (matches dataset encoding)
MODE_MAP: dict = {1: "car", 2: "bus", 3: "air", 4: "rail"}
MODE_MAP_INV: dict = {"car": 1, "bus": 2, "air": 3, "rail": 4}
VALID_MODES: list = ["car", "bus", "air", "rail"]

# Socio-demographic columns (static per traveler)
DEMOGRAPHIC_COLS: list = ["female", "business", "income"]

# Mode availability flags
AVAILABILITY_COLS: list = ["av_car", "av_bus", "av_air", "av_rail"]

# Trip attribute columns grouped by mode
TRIP_ATTR_COLS: dict = {
    "car": ["time_car", "cost_car"],
    "bus": ["time_bus", "cost_bus", "access_bus"],
    "air": ["time_air", "cost_air", "access_air", "service_air"],
    "rail": ["time_rail", "cost_rail", "access_rail", "service_rail"],
}

# Flat list of all trip attribute columns (used for dtype conversion)
ALL_ATTR_COLS: list = (
    ["time_car", "cost_car"]
    + ["time_bus", "cost_bus", "access_bus"]
    + ["time_air", "cost_air", "access_air", "service_air"]
    + ["time_rail", "cost_rail", "access_rail", "service_rail"]
)

# Service level integer → label mapping (air and rail)
SERVICE_LABELS: dict = {1: "no-frills", 2: "wifi", 3: "meal service"}

# ─────────────────────────────────────────────────────────────────────────────
# OLLAMA — LOCAL OPEN-SOURCE LLaMA
# No API key required.  No rate limits.  Fully offline after model pull.
# The OpenAI-compatible endpoint (http://localhost:11434/v1) is used
# via the openai Python SDK by simply swapping base_url.
# ─────────────────────────────────────────────────────────────────────────────
OLLAMA_BASE_URL: str = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1")
OLLAMA_MODEL: str = os.getenv("OLLAMA_MODEL", "llama3.1")

# Number of past trips shown per traveler during persona inference
MAX_TRIP_SAMPLE: int = 5

# ─────────────────────────────────────────────────────────────────────────────
# SELF-INSTRUCT
# Number of diverse instruction templates generated by the meta-prompt.
# Each template is then filled with ALL train trips → NUM_TEMPLATES × N total.
# ─────────────────────────────────────────────────────────────────────────────
NUM_TEMPLATES: int = 50

# ─────────────────────────────────────────────────────────────────────────────
# TRAIN / TEST SPLIT
# ─────────────────────────────────────────────────────────────────────────────
TEST_SIZE: float = 0.2
RANDOM_STATE: int = 42

# ─────────────────────────────────────────────────────────────────────────────
# LORA FINE-TUNING  (HuggingFace; separate from Ollama inference)
# ─────────────────────────────────────────────────────────────────────────────
BASE_MODEL: str = "meta-llama/Meta-Llama-3-8B-Instruct"
HF_TOKEN: str = os.getenv("HF_TOKEN", "")  # required for gated HF models

LORA_R: int = 8
LORA_ALPHA: int = 16
LORA_DROPOUT: float = 0.05
TARGET_MODULES: list = ["q_proj", "v_proj", "k_proj", "o_proj"]

BATCH_SIZE: int = 4
GRAD_ACCUM: int = 4       # effective batch = BATCH_SIZE * GRAD_ACCUM = 16
LEARNING_RATE: float = 2e-4
EPOCHS: int = 3
MAX_SEQ_LEN: int = 1024
WARMUP_RATIO: float = 0.05
LR_SCHEDULER: str = "cosine"

# ─────────────────────────────────────────────────────────────────────────────
# VALIDATION HELPER
# ─────────────────────────────────────────────────────────────────────────────
def validate_config() -> bool:
    """
    Check all critical settings before pipeline starts.
    Prints warnings for fixable issues, raises for blocking ones.
    """
    import urllib.request

    ok = True

    # Check DATA_TYPE
    if DATA_TYPE not in ["SP_ONLY", "RP_ONLY", "BOTH"]:
        print(f"  [ERROR] DATA_TYPE='{DATA_TYPE}' is invalid. Use SP_ONLY | RP_ONLY | BOTH")
        ok = False

    # Check Ollama server is reachable
    try:
        tags_url = OLLAMA_BASE_URL.rstrip("/v1").rstrip("/") + "/api/tags"
        urllib.request.urlopen(tags_url, timeout=3)
        print(f"  [OK]    Ollama server reachable at {OLLAMA_BASE_URL}")
    except Exception:
        print(f"  [WARN]  Ollama server not detected at {OLLAMA_BASE_URL}")
        print("          Install: https://ollama.com/download")
        print(f"          Pull  : ollama pull {OLLAMA_MODEL}")
        print("          Start : ollama serve")

    # Check raw data file
    if not os.path.exists(DATA_PATH):
        print(f"  [ERROR] Raw data not found: {DATA_PATH}")
        ok = False
    else:
        print(f"  [OK]    Raw data found: {DATA_PATH}")

    return ok
